all:
	@echo "Available targets: clean, fclean"

fclean:
	@$(MAKE) -s -C ex00 fclean
	@$(MAKE) -s -C ex01 fclean
	@$(MAKE) -s -C ex02 fclean
	@echo "fclean completed for all projects."

clean:
	@$(MAKE) -s -C ex00 clean
	@$(MAKE) -s -C ex01 clean
	@$(MAKE) -s -C ex02 clean
	@echo "clean completed for all projects."

.PHONY:		all clean fclean